name: RethinkTech
favicon: null
layout_spectrum: 0.6028
typography_spectrum: 0.6668305969797075
title: Technology.Gaming.Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#071a29'
    - '#102b3e'
    - '#2d4b67'
    - '#516f8b'
  brandStrength: 0.8941486801486462
  lightness: 0.7060371171683073
  saturation: 0.42895686416886747
  rhythmicContrast: 0.4930069949477911
purpose: []
