analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#575757'
    - '#169ccf'
    - '#5ebbde'
  brandStrength: 0.875
  lightness: 0.25
  rhythmicContrast: 0.971217
  saturation: 0
cta: {}
layout_spectrum: 0.25949
name: RethinkTech
opengraph: {}
purpose: []
typography_spectrum: 0.52956
