name: RethinkTech
favicon: null
layout_spectrum: 0.25949
typography_spectrum: 0.52956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#0f405f'
    - '#929292'
    - '#01afdc'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.971217
purpose: []
