name: RethinkTech
favicon: null
layout_spectrum: 0.19326
typography_spectrum: 0.63913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#0f405f'
    - '#929292'
    - '#01afdc'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
