name: RethinkTech
favicon: null
layout_spectrum: 0.25949
typography_spectrum: 0.52956
title: Technology.Gaming.Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29292d'
    - '#63b4d1'
    - '#960606'
    - '#ffffff'
    - '#b95b5b'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
