name: RethinkTech
favicon: null
layout_spectrum: 0.86875
typography_spectrum: 0.64996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#1d2e3e'
    - '#0e9fb4'
    - '#8a8e93'
    - '#ebb26c'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
