name: RethinkTech
favicon: null
layout_spectrum: 0.04650712315924466
typography_spectrum: 0.6668305969797075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8941486801486462
  lightness: 0.7060371171683073
  saturation: 0.42895686416886747
  rhythmicContrast: 0.4930069949477911
purpose: []
