name: RethinkTech
favicon: null
layout_spectrum: 0.86875
typography_spectrum: 0.64996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9c87b'
    - '#161220'
    - '#984b45'
    - '#9da3a8'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
